### ISSUE TITLE
Specify version of dependencies (tensorflow)

### ISSUE THREAD

**Issue by Joetib** [jackfrost1411/facial-recognition-login#2]
I tried running the flask server after installing Tensorflow and flask. However execution fails with message that `tf.get_default_graph` does not exist. 
Knowing the exact version used, will be very helpful.
Thank you

**Comment by Joetib** [comment]
Well I managed to get past this error with `tf.compat.v1.get_default_graph()` but 

```python
model = tf.keras.models.load_model('facenet_keras.h5')
```
Fails with error 
`ValueError: bad marshal data (unknown type code)`

**Comment by jackfrost1411** [comment]
Please ask this question on StackOverflow as there is a larger community to solve your query. I am sure this error is not this project-specific!

**Comment by Joetib** [comment]
I realized where the issue was, it want the codebase it was just some bit of confusion on what version of tensorflow to use. The project runs on tensorflow <2 version.
It would be great if there was a requirements file that pinned down exact required versions of packages
